### ISSUE TITLE
Removing curb dependency / JRuby support

### ISSUE THREAD

**Issue by dqdinh** [digidentity/libsaml#126]
Hi, I want use libsaml with JRuby but JRuby does not support C extensions in the 'curb' gem.

Why is curb a required dependency in the gemspec? I looked through the source and can't find anything that depends on curb.

Would you be OK with a pull request to remove curb?

Thanks.

**Comment by dqdinh** [comment]
Actually, a bunch of tests fail when switching to JRuby. I'm currently looking into the cause.

`Finished in 27.94 seconds (files took 13.58 seconds to load)
831 examples, 51 failures

Failed examples:

rspec ./spec/lib/saml/base_spec.rb:67 # BaseDummy parse override preserves the original value
rspec ./spec/lib/saml/bindings/http_post_spec.rb:22 # Saml::Bindings::HTTPPost.create_form_attributes signs the document
rspec ./spec/lib/saml/bindings/http_post_spec.rb:18 # Saml::Bindings::HTTPPost.create_form_attributes adds the relay_state
rspec ./spec/lib/saml/bindings/http_post_spec.rb:34 # Saml::Bindings::HTTPPost.create_form_attributes creates a notification
rspec ./spec/lib/saml/bindings/http_post_spec.rb:14 # Saml::Bindings::HTTPPost.create_form_attributes creates a hash with the destination as url
rspec ./spec/lib/saml/bindings/http_post_spec.rb:29 # Saml::Bindings::HTTPPost.create_form_attributes sets the SAMLRequest variable if the message is a request
rspec ./spec/lib/saml/bindings/http_post_spec.rb:52 # Saml::Bindings::HTTPPost.receive_message it verifies the xml
rspec ./spec/lib/saml/bindings/http_post_spec.rb:67 # Saml::Bindings::HTTPPost.receive_message creates a notification
rspec ./spec/lib/saml/bindings/http_post_spec.rb:63 # Saml::Bindings::HTTPPost.receive_message sets the actual destination on the message
rspec ./spec/lib/saml/bindings/http_post_spec.rb:59 # Saml::Bindings::HTTPPost.receive_message returns the parsed message
rspec ./spec/lib/saml/bindings/http_post_spec.rb:48 # Saml::Bindings::HTTPPost.receive_message has no errors when signature is valid
rspec ./spec/lib/saml/bindings/http_redirect_spec.rb:67 # Saml::Bindings::HTTPRedirect.create_url adds the signature
rspec ./spec/lib/saml/bindings/http_redirect_spec.rb:98 # Saml::Bindings::HTTPRedirect.create_url with block uses the block to create the signature
rspec ./spec/lib/saml/bindings/http_redirect_spec.rb:83 # Saml::Bindings::HTTPRedirect.create_url with sha256 calculates the signature with sha256
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:72 # Saml::Bindings::HTTPArtifact.receive_message adds an error if the signature is invalid
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:77 # Saml::Bindings::HTTPArtifact.receive_message creates a notification
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:64 # Saml::Bindings::HTTPArtifact.receive_message returns an artifact resolve
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:68 # Saml::Bindings::HTTPArtifact.receive_message verifies the signature in the artifact resolve
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:31 # Saml::Bindings::HTTPArtifact.create_response returns the response xml
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:35 # Saml::Bindings::HTTPArtifact.create_response returns the content type
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:118 # Saml::Bindings::HTTPArtifact.resolve with valid response sends the artifact_resolve to the identity provider
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:113 # Saml::Bindings::HTTPArtifact.resolve with valid response signs the artifact resolve
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:108 # Saml::Bindings::HTTPArtifact.resolve with valid response creates a signed artifact_resolve message
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:125 # Saml::Bindings::HTTPArtifact.resolve with valid response returns the response
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:87 # Saml::Bindings::HTTPArtifact.resolve notifications creates a notification
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:138 # Saml::Bindings::HTTPArtifact.resolve with invalid response adds an error if the signature is invalid
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:21 # Saml::Bindings::HTTPArtifact.create_response_xml signs the response xml
rspec ./spec/lib/saml/bindings/http_artifact_spec.rb:25 # Saml::Bindings::HTTPArtifact.create_response_xml creates a notification
rspec ./spec/lib/saml/bindings/soap_spec.rb:13 # Saml::Bindings::SOAP.create_response_xml signs the response xml
rspec ./spec/lib/saml/bindings/soap_spec.rb:17 # Saml::Bindings::SOAP.create_response_xml creates a notification
rspec ./spec/lib/saml/bindings/soap_spec.rb:26 # Saml::Bindings::SOAP.post_message creates a notification
rspec ./spec/lib/saml/bindings/soap_spec.rb:79 # Saml::Bindings::SOAP.post_message with invalid signature adds an error if the signature is invalid
rspec ./spec/lib/saml/bindings/soap_spec.rb:55 # Saml::Bindings::SOAP.post_message with valid response verifies the signature in the artifact response
rspec ./spec/lib/saml/bindings/soap_spec.rb:66 # Saml::Bindings::SOAP.post_message with valid response returns the logout_response
rspec ./spec/lib/saml/bindings/soap_spec.rb:45 # Saml::Bindings::SOAP.post_message with valid response creates a signed logout_request message
rspec ./spec/lib/saml/bindings/soap_spec.rb:59 # Saml::Bindings::SOAP.post_message with valid response sends the logout_request to the request destination
rspec ./spec/lib/saml/bindings/soap_spec.rb:50 # Saml::Bindings::SOAP.post_message with valid response signs the artifact resolve
rspec ./spec/lib/saml/bindings/soap_spec.rb:111 # Saml::Bindings::SOAP.receive_message creates a notification
rspec ./spec/lib/saml/bindings/soap_spec.rb:93 # Saml::Bindings::SOAP.receive_message with valid signature returns a logout request
rspec ./spec/lib/saml/bindings/soap_spec.rb:97 # Saml::Bindings::SOAP.receive_message with valid signature verifies the signature in the artifact response
rspec ./spec/lib/saml/bindings/soap_spec.rb:103 # Saml::Bindings::SOAP.receive_message with invalid signature adds an error if the signature is invalid
rspec ./spec/lib/saml/util_spec.rb:290 # Saml::Util.verify_xml response returns the signed message type
rspec ./spec/lib/saml/util_spec.rb:283 # Saml::Util.verify_xml response verifies all the signatures in the file
rspec ./spec/lib/saml/util_spec.rb:304 # Saml::Util.verify_xml assertion verifies all the signatures in the file
rspec ./spec/lib/saml/util_spec.rb:311 # Saml::Util.verify_xml assertion returns the signed message type
rspec ./spec/lib/saml/util_spec.rb:327 # Saml::Util.verify_xml authn request within an artifact response parses the authn request from the signed XML without an undefined samlp prefix error
rspec ./spec/lib/saml/util_spec.rb:38 # Saml::Util authn_request .sign_xml "format" parameter when a format is given formats the message as the given format
rspec ./spec/lib/saml/util_spec.rb:31 # Saml::Util authn_request .sign_xml "format" parameter when no format is given formats the message as xml by default
rspec ./spec/lib/saml/util_spec.rb:73 # Saml::Util authn_request .sign_xml "include_nested_prefixlist" parameter when disabled adds the default prefixlists to the unsigned signatures
rspec ./spec/lib/saml/util_spec.rb:57 # Saml::Util authn_request .sign_xml "include_nested_prefixlist" parameter when enabled by config adds the nested and the default prefixlists to the unsigned signatures
rspec ./spec/lib/saml/util_spec.rb:65 # Saml::Util authn_request .sign_xml "include_nested_prefixlist" parameter when enabled by parameter adds the nested and the default prefixlists to the unsigned signatures`

**Comment by dqdinh** [comment]
The test errors revolve around two issues: missing method `content` and encoded signature inequality. @benoist: Any ideas why?

```
NoMethodError:
        undefined method `content' for nil:NilClass
      # ./lib/saml/util.rb:57:in `sign_xml'
      # ./spec/lib/saml/bindings/http_artifact_spec.rb:58:in `block in body'
      # ./spec/lib/saml/bindings/http_artifact_spec.rb:61:in `block in request'
      # ./spec/lib/saml/bindings/http_artifact_spec.rb:62:in `block in message'
      # ./spec/lib/saml/bindings/http_artifact_spec.rb:78:in `block in (root)'
      # ./spec/support/notification_matcher.rb:12:in `block in matches?'
      # ./spec/support/notification_matcher.rb:11:in `matches?'
      # ./spec/lib/saml/bindings/http_artifact_spec.rb:78:in `block in (root)'
```

```
    expected: "HliUb3I3Uksgc1O6lxpPb%2Bnj%2FTykWLrWnw%2BnduLfF70Qf8LeCJuP6HDJSe9s%0AS9wR2rO9jFl8cuqg2AM6RuOOju%2FNWriEKIWECbMmUvJWpqeWU0IDKYHe47uv%0AAhVfPRyckfmDH2dhKW9ExJjKBlwr6SencuoZlte1uU1TqzKnnH8%3D"
             got: "oWkIRjOIKQQ7IZfyLJwQ0w2wsI68p8D4Bl1gBPEIKJ4fhqLws6dppyOPENcv%0ALSNZj%2F%2Fs5%2FnMAbrQN9%2FhOqKd2oS2%...Bwc9aZiZp3%2FUsFQz%2BTnA9PxbWSgCWI%2Fq%0ABNc0ulN3NOTEPMv%2F5QQaDGCozU%2F8dZIWIfYFTw39bNFvsj500Ko%3D" (using ==)
```

**Comment by benoist** [comment]
I can only think that the problems are with xmldsig and xmlmapper. Libsaml doens't do anything special with xml it just implements the SAML specs. Issue #115 might have something to do with these errors.

**Comment by dqdinh** [comment]
@benoist - thanks for commenting out the curb dev dependency.

**Comment by benoist** [comment]
Can we close this?
