### ISSUE TITLE
Rails 5 deprecation warnings

### ISSUE THREAD

**Issue by gyng** [digidentity/libsaml#129]
Rails 5.0.0.1 throws the warning when used with libsaml:

> DEPRECATION WARNING: before_filter is deprecated and will be removed in Rails 5.1. Use before_action instead.

The warning is thrown inside [`controller_helper.rb`](https://github.com/digidentity/libsaml/blob/master/lib/saml/rails/controller_helper.rb). `before_action` is not available in Rails 3, which, according to the gemspec, is supported by libsaml.

Will libsaml up the Rails requirement to Rails 4? I updated activemodel and activesupport to >=4 and tests are still passing. While just annoying right now, it will break with Rails 5.1.

**Comment by benoist** [comment]
I think we can create a separate branch for < Rails 4.2 for however uses it. But I will upgrade the gemspec to require at least Rails 4.2 to stay inline with the Rails maintenance policy.
I will make a major release version for this change.

**Comment by benoist** [comment]
Separate branch is created an deprecation warnings have been removed. We will do some tests in our own applications to check for any issues before releasing
