### ISSUE TITLE
AttributeValue for assertion attributes doesn't have "type" set

### ISSUE THREAD

**Issue by andrii-rymar** [digidentity/libsaml#134]
I'm using libsaml in my mock identity provider and have an issue with custom attributes.
Adding an additional attribute to the assertion, like:
```
assertion.add_attribute('FirstName', 'John')
```
produces SAMLResponse with such element:
```
<saml:Attribute Name="FirstName">
    <saml:AttributeValue>John</saml:AttributeValue>
</saml:Attribute>
```
which causes my service provider (based on OpenSAML) to crash with error:
> java.lang.ClassCastException: org.opensaml.xml.schema.impl.XSAnyImpl cannot be cast to org.opensaml.xml.schema.impl.XSStringImpl

Comparing with SAMLResponse from other providers (like SSOCircle) I figured out that "type" attribute should be set for the value, like:
```
<saml:Attribute Name="FirstName">
    <saml:AttributeValue xsi:type="xs:string">John</saml:AttributeValue>
</saml:Attribute>
```
Saml::Elements::AttributeValue class has such attribute but it is not filled during initialization.

Currently I'm using a dirty hack setting this attribute in the [Saml::ComplexTypes::AttributeType](https://github.com/digidentity/libsaml/blob/master/lib/saml/complex_types/attribute_type.rb#L34):
```
def attribute_value=(value)
    attribute_value = if value.is_a? String
      Saml::Elements::AttributeValue.new(content: value, type: 'xs:string')
    else
      value
    end
    self.attribute_values = [attribute_value]
end
```
but maybe there are other ways to deal with the problem?

**Comment by benoist** [comment]
I've added the option to add the type attribute when using the add_attribute method see example:
```ruby
assertion.add_attribute('FirstName', 'John', type: 'xsi:string')
```
