### ISSUE TITLE
Sign using SHA1

### ISSUE THREAD

**Issue by luis-cbqa** [digidentity/libsaml#146]
Currently, I only see the algorithm used to sign the saml is SHA256, but I need to sign it by using SHA1, that feature is implemented? I don´t see it, if not I can do a PR with it

**Comment by luis-cbqa** [comment]
it should be enough if I change the value of
```
signature.signed_info.signature_method.algorithm
signature.signed_info.reference.digest_method.algorithm
```
right?

I'm, just saying

**Comment by jdongelmans** [comment]
Since SHA1 is [proven](https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html) to be vulnerable to collision attacks, I think it's not desired to add support for this and I would advise you to steer away from this implementation.

If you are _really_ in need of SHA1, you can indeed change the values you suggested.

**Comment by luis-cbqa** [comment]
I see, however, I really need SHA1 implementation, I want to test an SP SSO feature with all possible permutations and one of them is using SHA1 as the signature algorithm.

now, should I make a PR with those changes? or is better to the gem if I fork this repo and use the fork with my own implementation?

NOTE: I'm newbie about GitHub forks and contributing :P

**Comment by benoist** [comment]
What do you need to sign with SHA1 exactly?

HTTP::Redirect binding for requests still use SHA1 as a default.
HTTP::Post and HTTP::Artifact use a SHA256 as a default.

I agree with @jdongelmans that you shouldn't use SHA1, but to make it easier to support different signature algorithms, we could add a global configuration to set the methods. The XMLDSig library already supports SHA256, SHA384, SHA512 and SHA1. So adding an easy way to use the longer hashes, we would need to add the configuration anyway.

**Comment by benoist** [comment]
option added in 3.0.7

**Comment by luis-cbqa** [comment]
thanks guys! I'll take a look at it :), and answer your question @benoist , I just need to test an SSO feature from a partner's app, so I need to create a signed SAML as Okta or any other IdP does, by using SHA1 or SHA256, that's why I needed to sign it with SHA1
