### ISSUE TITLE
xmldsig dependency issue

### ISSUE THREAD

**Issue by jaypatrickhoward** [digidentity/libsaml#148]
Any chance of a new 2.24.2 version that updates the xmldsig dependency from `'~> 0.5.1'` to `'~> 0.6.0'`?

The reason I ask:  I'm dealing with a project that's still stuck on Rails3, but I'd like to take advantage of nokogiri 1.8.0.  I can't because:

libsaml 2.24.1 is the highest version that doesn't require Rails4 and it depends on xmldsig `'~> 0.5.1'`.

xmldsig 0.5.1 is the latest 0.5.x.  It depends on nokogiri `'~> 1.6.8'`.  This dependency is changed to `'< 2.0.0, >= 1.6.8'` in xmldsig 0.6.3, which would allow for newer versions of nokogiri, but libsaml 2.24.1 prevents xmldsig from going up to 0.6.3.

**Comment by benoist** [comment]
It's pushed! Enjoy :)

**Comment by jaypatrickhoward** [comment]
Not to look a gift horse in the mouth, but I may have suggested the wrong dependency constraint.  Instead of "~> 0.6.0", it might should be ">= 0.5.1, < 0.7.0" instead.  That supports xmldsig 0.6.x versions, but also the 0.5.1 (and higher) versions we already know work.  Just wanted to mention it.  Thanks for looking at the original issue.

**Comment by benoist** [comment]
Haha no worries, plenty more horses left in the stables. 2.24.3 is pushed.

**Comment by jaypatrickhoward** [comment]
It's just a question of risk.  ">= 0.5.1, < 0.7.0" is "conservative" and only makes the assumption that xmldsig won't break libsaml support in the 0.6.x release cycle.  You could also throw caution to the wind and make it ">= 0.5.1", but that could cause problems later if some future version of xmldsig removes something libsaml depends on.

**Comment by benoist** [comment]
As the writer of xmldsig I can make sure breaking changes go in 0.7.0.

**Comment by jaypatrickhoward** [comment]
Hah!  I didn't realize you were responsible for both gems.  You'd know best which constraints to use in libsaml then.  Thanks again.
