### ISSUE TITLE
Support multiple entity descriptors in metadata when using Url ProviderStore

### ISSUE THREAD

**Issue by aukevs** [digidentity/libsaml#150]
I am considering a use case with multiple entity descriptors in one metadata file. I think it's part of the SAML specification. I was thinking about adding some features to the Url provider store to support it. Might also be nice to have some sort of caching mechanism in there. 

Thoughts?

**Comment by benoist** [comment]
Yeah that could definitely be nice. The provider base class can already support 2 types in one entity descriptor
