### ISSUE TITLE
KeyInfo node in EncryptedData node

### ISSUE THREAD

**Issue by luis-cbqa** [digidentity/libsaml#151]
Hey, guys! 

Let me explain myself before doing my question:

Playing as an IdP (I am testing a SP application) I created, signed and encrypted a SAML document so the EncryptedData node result is something like this:
```
<xenc:EncryptedData Id="_e9bc13fa4e" Type="http://www.w3.org/2001/04/xmlenc#Element">
    <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
    <xenc:CipherData>
        <xenc:CipherValue>...
        </xenc:CipherValue>
    </xenc:CipherData>
</xenc:EncryptedData>
```

However, when I use Okta the generated SAML response has this:
```
<xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="_3bfac90f8f5bcec1ccbbcd65c35b9c58" Type="http://www.w3.org/2001/04/xmlenc#Element">
    <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"/>
    <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:RetrievalMethod Type="http://www.w3.org/2001/04/xmlenc#EncryptedKey" URI="#_931a8a29943a8407a4de23276473c22b"/>
    </ds:KeyInfo>
    <xenc:CipherData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#">
        <xenc:CipherValue>...</xenc:CipherValue>
    </xenc:CipherData>
</xenc:EncryptedData>
```

As you can see in my SAML response the ds:KeyInfo node is missing, now when I send my encrypted SAML response to the SP I am testing, it always fails when trying to validate the XML because the SP is using ruby-saml gem to validate the XML and I notice the ruby-saml gem is expecting for the KeyInfo node to decrypt the assertion, if the response does not have it, it fails to decrypt it.

Now, my question is: is there a way to add the KeyInfo data when encrypting an assertion?

Thanks in advance

**Comment by benoist** [comment]
That is possible to do.
Create an encrypted data object before encrypting the data like so:

```ruby
encrypted_data = Xmlenc::Builder::EncryptedData.new
encrypted_data.set_key_retrieval_method Xmlenc::Builder::RetrievalMethod.new(
   uri: "#<key_id>"
)
encrypted_data.set_encryption_method(
   algorithm: 'http://www.w3.org/2001/04/xmlenc#aes256-cbc'
)
```

There is a Util function that can encrypt assertions for you, however it currently does not have the option to add key info.
https://github.com/digidentity/libsaml/blob/7110809b921e00d894aa42d72cc67c32be9a52f8/lib/saml/util.rb#L63

There is also a Util function to encrypt name ids with key info options. This eventually creates an EncryptedData object that contains the key info.
https://github.com/digidentity/libsaml/blob/master/lib/saml/elements/encrypted_id.rb#L40

I suppose the encrypted assertion can be extended to allow these options as well.
In the mean time I'd suggest to use the code from the encrypt_assertion function and add the key_retrieval_method yourself.

**Comment by luis-cbqa** [comment]
I see, actually I am using the encrypt_assertion method for encrypting the assertion, I just noticed the KeyInfo stuff.

I'll do what you suggest.

Thanks @benoist

**Comment by benoist** [comment]
Did you manage to get it working?

**Comment by luis-cbqa** [comment]
Yes, I did, your solution worked perfectly!

**Comment by luis-cbqa** [comment]
I just had to add a '#' to the uri

`encrypted_data.set_key_retrieval_method (Xmlenc::Builder::RetrievalMethod.new(uri: "##{key_name}"))`

and add the same key_name to the encrypted key id

`encrypted_key.id = key_name`

resulting in:

```
def encrypt_assertion(assertion, key_descriptor_or_certificate)
        case key_descriptor_or_certificate
          when OpenSSL::X509::Certificate
            certificate = key_descriptor_or_certificate
            key_name    = "fd29bfcb991da2e156d1383a165b0f5705b18a49" #This is just a random number it will be anything :)
          when Saml::Elements::KeyDescriptor
            certificate = key_descriptor_or_certificate.certificate
            key_name    = key_descriptor_or_certificate.key_info.key_name
          else
            fail ArgumentError, "Expecting Certificate or KeyDescriptor got: #{key_descriptor_or_certificate.class}"
        end

        assertion = assertion.to_xml(nil, nil, false) if assertion.is_a?(Saml::Assertion) # create xml without instruct

        encrypted_data = Xmlenc::Builder::EncryptedData.new
        encrypted_data.set_key_retrieval_method (Xmlenc::Builder::RetrievalMethod.new(uri: "##{key_name}"))
        encrypted_data.set_encryption_method(algorithm: 'http://www.w3.org/2001/04/xmlenc#aes128-cbc')

        encrypted_key = encrypted_data.encrypt(assertion.to_s)
        encrypted_key.set_encryption_method(algorithm:               'http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p',
                                            digest_method_algorithm: 'http://www.w3.org/2000/09/xmldsig#sha1')

        encrypted_key.id = key_name
        encrypted_key.encrypt(certificate.public_key)

        Saml::Elements::EncryptedAssertion.new(encrypted_data: encrypted_data, encrypted_keys: encrypted_key)
      end
```
