### ISSUE TITLE
chomp vs gsub("\n", "") on Base64 encoding

### ISSUE THREAD

**Issue by aukevs** [digidentity/libsaml#152]
Hi there, 

The SAML specification says when encoding base64 in urls linefeeds or other whitepsace MUST be removed from the result. Libsaml is using `Base64.encode64(string).chomp` which only removes the '\n' at the end of the string, is this on purpose?

https://www.oasis-open.org/committees/download.php/35387/sstc-saml-bindings-errata-2.0-wd-05-diff.pdf

The compressed data is subsequently base64-encoded according to the rules specified in IETF
RFC 2045 [RFC2045]. Linefeeds or other whitespace MUST be removed from the result.

**Comment by benoist** [comment]
Yeah I guess we should really use Base64.strict_encode64

**Comment by aukevs** [comment]
Looks like it's a matter of changing that line in `def self.encode_64 string` and generating new signatures for the http_redirect_spec.rb
