### ISSUE TITLE
ECP profile support?

### ISSUE THREAD

**Issue by nov** [digidentity/libsaml#159]
Hi, I'm now working on SAML ECP implementation (for O365 users who uses Thunderbird).
It seems ECP isn't supported by this gem.
Do you have any plan for that?

**Comment by benoist** [comment]
We have no plans to add support, but as you noticed I'm happy to accept PR's 👍

**Comment by nov** [comment]
Thanks!

**Comment by benoist** [comment]
Let me know when you want a new gem version released :)

**Comment by nov** [comment]
I see.
I'll ping you once our QA team finished O365 integration tests.

**Comment by nov** [comment]
Hi, please release new version of `libsaml` gem.
thanks!

**Comment by jdongelmans** [comment]
@nov done, version 3.2.3 is now on Rubygems

**Comment by jdongelmans** [comment]
@nov done, version 3.2.3 is now on Rubygems! :)

**Comment by nov** [comment]
thanks!
