### ISSUE TITLE
Support for SAML responses where only the assertion is signed

### ISSUE THREAD

**Issue by lukad** [digidentity/libsaml#162]
Hi there,

I'm using this lib to implement SSO in our application. One of our clients does not sign their whole HTTP Post SAML response but only the assertion and this doesn't seem to be supported by libsaml.
`Saml::Util.verify_xml` [expects the whole message to be signed](https://github.com/digidentity/libsaml/blob/157c870da850e109b19987b4cf1e757a0b419902/lib/saml/util.rb#L126) but I don't understand why. Is it really necessary?

Regardless, we have asked our client to sign the complete message so this should not be a problem for us.

I'm just asking here because I don't understand why `Saml::Util.verify_xml` requires the message to be signed like this and I would be happy if someone could explain this to me.

And maybe this case should be handle explicitly because right now it will just blow up on [`signed_node.canonicalize`](https://github.com/digidentity/libsaml/blob/157c870da850e109b19987b4cf1e757a0b419902/lib/saml/util.rb#L128) (NoMethodError: undefined method `canonicalize' for nil:NilClass).

**Comment by benoist** [comment]
Sorry for the late reply.

It's a security consideration to verify the response message and the assertion.
That way we ensure nothing is injected/altered in the response message by a man in the middle. For instance you could alter the in_response_to id in the SAMLResponse if it wasn't signed.

**Comment by lukad** [comment]
Thanks for the reply. That's makes a lot of sense, I was only thinking of the assertion.
