### ISSUE TITLE
Onelogin: undefined method `canonicalize' for nil:NilClass

### ISSUE THREAD

**Issue by truongnmt** [digidentity/libsaml#167]
I'm implementing libsaml as an SP provider. The configuration is the same as documentation:

https://github.com/truongnmt/ruby-saml-sample/tree/master/config

In `config/metadata` I have 2 IdPs metadata Azure and Onelogin.
On testing SSO with Onelogin, I got this error:

![image](https://user-images.githubusercontent.com/11817656/72716592-d5c81380-3bb5-11ea-9bb3-8c25501a7cce.png)

```ruby
def verify_xml(message, raw_body)
  document = Xmldsig::SignedDocument.new(raw_body)

  signature_valid = document.validate do |signature, data, signature_algorithm|
    node = document.signatures.find { |s| s.signature_value == signature }.signature.at_xpath('descendant::ds:KeyName', Xmldsig::NAMESPACES)
    key_name = node.present? ? node.content : nil

    message.provider.verify(signature_algorithm, signature, data, key_name)
  end

  fail Saml::Errors::SignatureInvalid unless signature_valid

  signed_node = document.signed_nodes.find { |node| node['ID'] == message._id }
  message.class.parse(signed_node.canonicalize, single: true)
end
```

> undefined method `canonicalize' for nil:NilClass

The error is this line `message.class.parse(signed_node.canonicalize, single: true)`

On testing SSO with Azure, I got this error:
![image](https://user-images.githubusercontent.com/11817656/72718741-de224d80-3bb9-11ea-8c0c-528b4be1cb85.png)
> AADSTS90015: Requested query string is too long.

Same code but I got SAML Request from Onelogin, while in Azure, the SAML Request is invalid.

**Comment by benoist** [comment]
It appears the message is not signed as it doesn't contain a signature node.
Please make sure the identity provider signs the saml response

**Comment by truongnmt** [comment]
Thanks for your fast reply. I will look into it. 
By the way, I have a sample project [here](https://github.com/truongnmt/ruby-saml-sample). Would you be so kind as to have a look, please! I'm trying to create a sample project running.

Also about the Azure IdP do you have any thought what would cause this? 
Thanks!

**Comment by truongnmt** [comment]
I did solve the problem authenticate using Azure IdP. Turn out that I use `HTTP Post Binding` instead of `HTTP Redirect Binding`.

**Comment by truongnmt** [comment]
> It appears the message is not signed as it doesn't contain a signature node.
Please make sure the identity provider signs the saml response

This is a response I got from IdP (Full response [here](https://gist.github.com/truongnmt/362e3ccc5c3049a952e0ad54a3c7b2d1))
![image](https://user-images.githubusercontent.com/11817656/72798241-fd86ac80-3c85-11ea-9fd6-e65e84eb4a79.png)

```ruby
signed_node = document.signed_nodes.find do |node|
  node['ID'] == message._id
end
message.class.parse(signed_node.canonicalize, single: true)
```

`signed_node` is `nil` so that we got the following error:
> NoMethodError: undefined method `canonicalize’ for nil:NilClass

```
node['ID'] = "_a2aec7e7-1843-443c-9af3-da94e69d5113"
message._id = "_cc074cf4-34f6-464e-a198-6440bd998b00"
```

`document` is class ` Xmldsig::SignedDocument`, `message` is class `Saml::Response`. I believe both should return this value `_a2aec7e7-1843-443c-9af3-da94e69d5113` which is the Response ID. Somehow `message._id` return `Assertion` 's ID, which makes `signed_node` nil. 

Can you explain the purpose of this comparison, what are we trying to get?

**Comment by benoist** [comment]
The assertion is signed, but the response is not signed.
This is not allowed in the POST binding. If you are using the redirect binding, the signature should be in the URL, but you have to use the Redirect binding response handler as well. In your example you use the POST Binding

**Comment by truongnmt** [comment]
https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-saml-protocol
> The cloud service (the service provider) uses an HTTP Redirect binding to pass an AuthnRequest (authentication request) element to Azure AD (the identity provider). Azure AD then uses an HTTP post binding to post a Response element to the cloud service

In the case of Azure:
- AuthnRequest: HTTP Redirect Binding
- Response: HTTP Post Binding

The response from Azure is using Post request. Even if I change to HTTPRedirect:
```ruby
...
elsif params["SAMLResponse"]
  @response = Saml::Bindings::HTTPRedirect.receive_message(request)
else
```

The parsed response is nil because after decode base64, then we decode gzip:
```
Saml::Encoding.decode_gzip(Saml::Encoding.decode_64(message))
```
That makes sense if the Response is Redirect Binding, however since the Response is Post, we don't deflate the response's params. So `decode_gzip` return nil.

**Comment by truongnmt** [comment]
> The assertion is signed, but the response is not signed. This is not allowed in the POST binding

Seem like Azure only sign the Assertion not the Response. 🤔

**Comment by truongnmt** [comment]
> The assertion is signed, but the response is not signed. This is not allowed in the POST binding.

Reading from the full [response](https://gist.github.com/truongnmt/362e3ccc5c3049a952e0ad54a3c7b2d1), seem like in mine case, Azure only signs the Assertion, not Response. 🤔

**Comment by truongnmt** [comment]
Ah! Got it, on signing option we have "Sign SAML response and assertion"

**Comment by benoist** [comment]
We are indeed a bit stricter as we stick to the SAML security guidelines by default.

**Comment by truongnmt** [comment]
Nothing much but what do you think about adding a notice about require "Sign SAML response and Assertion" in the README? That would save some time when implementing the library.

**Comment by benoist** [comment]
It's now added to the readme

**Comment by truongnmt** [comment]
Seem like not both SAML Response and Assertion signing is required. On Azure, I setup "Sign SAML response" only and the SAML Response is processed normally.

`Saml::Util.verify_xml` [expects the whole message to be signed](https://github.com/digidentity/libsaml/blob/157c870da850e109b19987b4cf1e757a0b419902/lib/saml/util.rb#L114-L129), Assertion signing is optional.

Please correct the readme 🙇 
https://github.com/digidentity/libsaml#caveats

> SAMLResponse ~~and Assertions~~ has to be signed as per the SAML security guidelines (Some IDP’s don’t do this by default and require special configuration)

**Comment by truongnmt** [comment]
> We are indeed a bit stricter as we stick to the SAML security guidelines by default.

@benoist Sorry for bring up the old thread. I would like to ask about libsaml signature validation.

Just to recap, as we discussed before, libsaml requires SAML Response to be signed. If IdP only sign Assertions without signing Response, the following exception will be raised: `undefined method `canonicalize' for nil:NilClass`. The problem I'm facing is that one of my IdP can't sign SAML Response, they only support sign Assertion. 

As you said we want to stick to SAML security guidelines by default. Can you show me which guidelines that we are talking about? (I did some search and can't find one about sign SAML Response or Assertion)
And by only signing Assertion (as default by most IdP), do we exposed to any vulnerabilities?

**Comment by jdongelmans** [comment]
Hi Truong,

Thanks for digging into this again. I took a look at the [OWASP "cheat-sheet" for SAML security](https://cheatsheetseries.owasp.org/cheatsheets/SAML_Security_Cheat_Sheet.html) and indeed they mention either signing the individual assertions _**or**_ the entire response. They do however say these guidelines apply to both redirect and post-binding which I find a bit odd, as they definitely have different attack vectors (and thus need different security).

Anyway, since now (at least 1) big IDP does not support this, we could maybe opt for a configurable verify method which defaults to the old behaviour and make mention of this in the readme?

@benoist do you have any objections to this?

**Comment by truongnmt** [comment]
> Anyway, since now (at least 1) big IDP does not support this

Would you mind naming it explicitly please? 👀

**Comment by benoist** [comment]
I have no objections to make it safe by default and have the possibility to turn it off via configuration.

**Comment by nov** [comment]
FYI: Now the exception is more straight forward.
https://github.com/digidentity/libsaml/pull/188

**Comment by p8** [comment]
Closing as #188 seems to fix this issue.
