### ISSUE TITLE
Questions about documentation

### ISSUE THREAD

**Issue by truongnmt** [digidentity/libsaml#168]
> By default this will use a SamlProvider model that uses the filestore, if you want a database driven model comment out the #provider_store function in the initializer and make a model that defines #find_by_entity_id:
```ruby
class SamlProvider < ActiveRecord::Base
  include Saml::Provider

  def self.find_by_entity_id(entity_id)
    find_by entity_id: entity_id
  end
end
```

I have several questions regarding the documentation:
- where is `#provider_store function`
- by "database-driven model" means that we don't save metadata files and save them in the database?

Thanks for your time!

**Comment by jdongelmans** [comment]
Just above the mention of `#provider_store function` in the README is the initializer which is meant by this.

And yes, you store the metadata in the database as shown by the sample you included here.

**Comment by truongnmt** [comment]
@jdongelmans 
You mean like this?

config/initializers/saml_config.rb:
```ruby
Saml.setup do |config|
  # config.register_store :file, Saml::ProviderStores::File.new("config/metadata", "config/ssl/key.pem"), default: true
end
```

>  you store the metadata in the database

Do you mean literally store the **file** identity_provider.xml in the database? 
Or we have fields such as entity_id, sso_url, slo_url, certificate ...

**Comment by benoist** [comment]
In the example you just gave, you are registering a File based storage, where the SAML metadata from ServiceProvider and IdentityProvider are stored in a specific folder.
File based storage is different from a database storage.

Database storage is not included and you have to implement a ProviderStore for the database. You can look at the URL store to see the most basic form. The method find_by_entity_id should return a BasicProvider. You can choose to store the full metadata XML file or the individual fields.

**Comment by truongnmt** [comment]
So if I store individual fields in the database, I get all fields then build XML string then create a EntityDescriptor object: `Saml::Elements::EntityDescriptor.parse(metadata_xml, single: true)` right?

**Comment by benoist** [comment]
Well that might not be the most efficient way to do it, but it would get the result you are looking for.

You can also construct the EntityDescriptor by just instantiating a new object and applying the separated database values to the correct fields, save creating and parsing XML.

You can also just store the metadata XML files in the database and you parse them from that.
This would make it easy to download a metadata file from a URL endpoint and store it in your database. This way you don't need to generate XML from database values and you just parse the result.

**Comment by truongnmt** [comment]
Thanks for your reply!

One more thing, assume we have this config initializer:

```ruby
Saml.setup do |config|
  config.register_store :database, Saml::ProviderStores::Database.new(), default: true
end
```

When the app starts to run, `Saml::ProviderStores::Database.initializer()` will load all providers from database then build `providers` instance variable right?

And when we add new provider we have to update this `providers` instance variable too right?

**Comment by benoist** [comment]
Thats up to how you implement the provider. 
For example if you have the columns entity_id and metadata_xml you can do the following.

```ruby
class SamlProvider < ActiveRecord::Base
  include Saml::Provider

  def self.find_by_entity_id(entity_id)
    find_by entity_id: entity_id
  end

  def entity_descriptor
    @entity_descriptor ||= Saml::Elements::EntityDescriptor.parse(metadata_xml, single: true)
  end
end
```

```ruby
Saml.setup do |config|
  config.register_store :saml_provider, SamlProvider, default: true
end
```

This will load the metadata on demand and allows you to update the metadata on fly without restarting the application

**Comment by truongnmt** [comment]
Ah got it! You totally got my point! Again I think this could be written in the README, very helpful I think.

**Comment by truongnmt** [comment]
@benoist 

On create AuthnRequest redirect URL, I got this following error:
```
NoMethodError - undefined method `sign' for nil:NilClass:
  libsaml (3.6.0) lib/saml/provider.rb:62:in `sign'
  libsaml (3.6.0) lib/saml/bindings/http_redirect.rb:106:in `signed_params'
  libsaml (3.6.0) lib/saml/bindings/http_redirect.rb:64:in `create_url'
  libsaml (3.6.0) lib/saml/bindings/http_redirect.rb:9:in `create_url'
```

The error is that the provider (SP) has no encryption key to sign. I load SP from the database without an encryption key.
```ruby
def signed_params
  signature = request_or_response.provider.sign(signature_algorithm, encoded_params)

  encoded_signature = CGI.escape(Saml::Encoding.encode_64(signature))

  "#{encoded_params}&Signature=#{encoded_signature}"
end
```

In my case, AuthnRequest doesn't need to be signed. Actually out IdP is Azure which said the following:
https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-saml-protocol#signature

> Signature
Don't include a Signature element in AuthnRequest elements, as Azure AD does not support signed authentication requests.

Also, I see that in URL provider_stores. When creating `BasicProvider`, the encryption signing key is nil
https://github.com/digidentity/libsaml/blob/e2d3e126fef84e489281efed08602202b41447eb/lib/saml/provider_stores/url.rb#L11

This means if SP metadata is downloaded, no signing key is provided (following the above code). I believe on signing AuthnRequest will have the same problem.

**Comment by benoist** [comment]
This library does not support creating unsigned AuthnRequests using the included bindings.
If you want to do it, you can either create a pull request with the changes or you can use the library without the binding in your code and just send the serialized AuthnRequest without signature.

**Comment by truongnmt** [comment]
Thanks for clearing out! I'll see if I could open a PR 💪

**Comment by truongnmt** [comment]
```ruby
class SamlProvider < ActiveRecord::Base
  include Saml::Provider

  def self.find_by_entity_id(entity_id)
    find_by entity_id: entity_id
  end

  def entity_descriptor
    @entity_descriptor ||= Saml::Elements::EntityDescriptor.parse(metadata_xml, single: true)
  end
end
```

On implementing the provider, may I ask about why I need to `include Saml::Provider"?

I'm curious about this line too: `@entity_descriptor ||= ...`
Why `||=`?

**Comment by benoist** [comment]
https://github.com/digidentity/libsaml/blob/master/lib/saml/provider.rb

This module contains a lot of functions required by the library. 
Using the ||= is just for caching purposes. Otherwise you are just parsing the XML every time you want something from the entity_descriptor

**Comment by truongnmt** [comment]
Thanks for you quick response. However, I still don't get the use case of the two. Here is my database provider:

```ruby
class SamlProvider < ApplicationRecord
  def self.find_by_entity_id(entity_id)
    provider = find_by(entity_id: entity_id)
    entity_descriptor = Saml::Elements::EntityDescriptor.parse(provider.metadata)
    type = entity_descriptor.sp_sso_descriptor.present? ? 'service_provider' : 'identity_provider'
    Saml::BasicProvider.new(entity_descriptor, nil, "identity_provider", nil)
  end
end
```

I don't think I need to `include Saml::Provider` and I don't see the purpose of 
defining `entity_descriptor` method 🤔.

**Comment by benoist** [comment]
Ok but now you're showing a completely different implementation.
In this case you don't need it...

**Comment by truongnmt** [comment]
My federation server is multi-tenanted, and SP and IdP are in 1-to-1 relation. So I design it that way @@

I'm wondering about which use case do you thinking of?

**Comment by benoist** [comment]
I afraid thats outside of our support range and is a decision that should be made by you or the system architect of your federation server.

**Comment by truongnmt** [comment]
Thanks for your response!

Just another question. 🙏

If I store provider in the database, every time I found a provider I have to query against the database. If I attempt to load all providers when app startup, just like File provider store, save all providers in a class variable, how the application know when to update those class variables? The same need may appear if we using File provider store.

**Comment by benoist** [comment]
These questions have nothing to do with the libsaml library I'm afraid. It's a generic question about using a database instead of a file on the system.

**Comment by truongnmt** [comment]
Ok got it! Thanks for your time anyway! 👍 ✨
