### ISSUE TITLE
Azure AADSTS700016: Application with identifier 'https://sts.windows.net/xxxx-xxxx-xxxx/' was not found in the directory 'xxxx-xxxx-xxxx'.

### ISSUE THREAD

**Issue by truongnmt** [digidentity/libsaml#169]
I have a [sample project](https://github.com/truongnmt/ruby-saml-sample) to test SAML Authentication using Azure as IdP. I have Azure metadata configuration saved as file in `config/metadata`.

After create AuthnRequest and send to Azure, I got this result from Azure:
> AADSTS700016: Application with identifier 'https://sts.windows.net/xxxx-xxxx-xxxx/' was not found in the directory 'xxxx-xxxx-xxxx'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.

![image](https://user-images.githubusercontent.com/11817656/72801532-fe6f0c80-3c8c-11ea-98ec-3105f074cac2.png)

I create AuthnRequest by this command:
```ruby
destination = Saml.current_provider.single_sign_on_service_url(Saml::ProtocolBinding::HTTP_REDIRECT)
authn_request = Saml::AuthnRequest.new(destination: destination)
```

The AuthnRequest issuer is taken from `current_provider` 's metadata. Which is IdP's entity id `https://sts.windows.net/xxxx-xxxx-xxxx/`. I think the right issuer should be the one who sent the request, which is the SP entity id: `'http://localhost:3000/saml/metadata'`.

With that thought in mind, I specify issuer:
```ruby
destination = Saml.current_provider.single_sign_on_service_url(Saml::ProtocolBinding::HTTP_REDIRECT)
authn_request = Saml::AuthnRequest.new(
    destination: destination,
    issuer: 'http://localhost:3000/saml/metadata'
)
```

However, when signing the SAML parameter, I got this error:
> Cannot find provider with entity_id: http://localhost:3000/saml/metadata

https://github.com/digidentity/libsaml/blob/master/lib/saml/bindings/http_redirect.rb#L105

Because I specify the issuer so it will use that issuer as entity id to find for provider in providers store. That means it's finding the SP's provider metadata, which is either wrong (should be Idp metadata) or it's don't exist (I don't add that in `config/metadata`).

If I change like this it's worked. The AuthnRequest is accepted by Azure.
```diff
      def signed_params
-        signature = request_or_response.provider.sign(signature_algorithm, encoded_params)
+        signature = Saml.current_provider.sign(signature_algorithm, encoded_params)

        encoded_signature = CGI.escape(Saml::Encoding.encode_64(signature))

        "#{encoded_params}&Signature=#{encoded_signature}"
      end

```

**Comment by benoist** [comment]
Thats incorrect, the current_provider has to be configured using the entity id of your service provider.

**Comment by truongnmt** [comment]
Oh got it! So we have to add IDPSSODescriptor into sp metadata right. So that `Saml.current_provider.single_sign_on_service_url` can return SSO URL to IdP.

**Comment by benoist** [comment]
No you have to add a SPSSODescriptor for the ServiceProvider Metadata.

**Comment by truongnmt** [comment]
The `single_sign_on_service_url()` method will find `idp_descriptor()`

```ruby
    def idp_descriptor(raise_error = true)
      entity_descriptor.idp_sso_descriptor || raise_error &&
          raise(Saml::Errors::InvalidProvider.new("Cannot find identity provider with entity_id: #{entity_id}"))
    end
```

Isn't finding IDPSSODescriptor in the metadata? 🤔 

Here is my `sp.xml` file:

```xml
<?xml version="1.0"?>
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata"
                     validUntil="2020-01-24T05:41:14Z"
                     cacheDuration="PT604800S"
                     entityID="https://localhost:4447/saml/metadata">
  <md:SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                            Location="https://localhost:4447/saml/logout"/>
    <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified</md:NameIDFormat>
    <md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                                 Location="https://localhost:4447/saml/acs"
                                 index="1"/>

  </md:SPSSODescriptor>
  <md:IDPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <md:KeyDescriptor use="signing">
      <md:KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
        <md:X509Data>
          <md:X509Certificate>
MIIC8DCCAdigAwIBAgIQc5ZjVSrAAbdBLLBSSGrUAzANBgkqhkiG9w0BAQsFADA0MTIwMAYDVQQDEylNaWNyb3NvZnQgQXp1cmUgRmVkZXJhdGVkIFNTTyBDZXJ0aWZpY2F0ZTAeFw0yMDAxMTQwNTIxNTFaFw0yMzAxMTQwxxxx          
          </md:X509Certificate>
        </md:X509Data>
      </md:KeyInfo>
    </md:KeyDescriptor>
    <md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                         Location="https://login.microsoftonline.com/xxxx/saml2"/>
    <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
                         Location="https://login.microsoftonline.com/xxxx/saml2"/>
    <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                         Location="https://login.microsoftonline.com/xxxx/saml2"/>
  </md:IDPSSODescriptor>
</md:EntityDescriptor>
```

**Comment by benoist** [comment]
No you need to have 2 separate entity descriptors.

The service provider has it's own entity id and also requires an EntityDescriptor with SPSSODescriptor

The identity provider has another entity id and requires an EntityDescriptor with IDPSSODescriptor

As you are implementing a ServiceProvider, you need to register your current_provider with your own entity_id

In the request_authenication method you need to use the IDP's entity to find the Saml.provider


```ruby
class SamlController < ApplicationController
  extend Saml::Rails::ControllerHelper
  current_provider "<your_sp_entity_id>"

  def request_authentication
    provider = Saml.provider("<the_idp_entity_id>")
    destination = provider.single_sign_on_service_url(Saml::ProtocolBinding::HTTP_POST)

    authn_request = Saml::AuthnRequest.new(destination: destination)

    session[:authn_request_id] = authn_request._id

    @saml_attributes = Saml::Bindings::HTTPPost.create_form_attributes(authn_request)

    render text: @saml_attributes.to_yaml
  end
```

**Comment by truongnmt** [comment]
That would make a lot of sense! Thanks for clearing out! Again, have some guidance about this in the Readme is super helpful!
