### ISSUE TITLE
Question about SAML Response validation

### ISSUE THREAD

**Issue by truongnmt** [digidentity/libsaml#170]
When receiving response message, I only see that we verify the XML only
https://github.com/digidentity/libsaml/blob/e2d3e126fef84e489281efed08602202b41447eb/lib/saml/bindings/http_post.rb#L35

What about other validations?
- response's state
- SAML version
- condition
- response id
- success status
- in response to
- audience
- response's issuer
- ...

Is this validation is DIY or `libsaml` already do these validations?

**Comment by benoist** [comment]
Thats up to you to verify as everyone will have different solution in terms of storage and rules to apply..
