### ISSUE TITLE
Add element SessionNotOnOrAfter

### ISSUE THREAD

**Issue by truongnmt** [digidentity/libsaml#172]
From SAML core spec:
> SessionNotOnOrAfter [Optional]
>
> Specifies a time instant at which the session between the principal identified by the subject and the SAML authority issuing this statement MUST be considered ended. The time value is encoded in UTC, as described in Section 1.3.3. There is no required relationship between this attribute and a NotOnOrAfter condition attribute that may be present in the assertion.

I'm about to validate this attribute from the assertion just to find out that we haven't had `SessionNotOnOrAfter` element yet.

https://github.com/digidentity/libsaml/blob/e2d3e126fef84e489281efed08602202b41447eb/lib/saml/elements/authn_statement.rb
```ruby
module Saml
  module Elements
    class AuthnStatement
      include Saml::Base

      tag "AuthnStatement"
      namespace 'saml'

      attribute :authn_instant, Time, tag: "AuthnInstant", on_save: lambda { |val| val.utc.xmlschema }
      attribute :session_index, String, tag: "SessionIndex"

      has_one :subject_locality, Saml::Elements::SubjectLocality, tag: "SubjectLocality"
      has_one :authn_context, Saml::Elements::AuthnContext, tag: "AuthnContext"

      validates :authn_instant, :authn_context, presence: true

      def initialize(*args)
        options = args.extract_options!
        @subject_locality = Saml::Elements::SubjectLocality.new(address: options.delete(:address)) if options[:address]
        @authn_context = Saml::Elements::AuthnContext.new(authn_context_class_ref: options.delete(:authn_context_class_ref)) if options[:authn_context_class_ref]
        super(*(args << options))
      end
    end
  end
end
```

Would you please confirm this? Thanks!

**Comment by jdongelmans** [comment]
Fixed in [v3.9.1](https://github.com/digidentity/libsaml/releases/tag/v3.9.1)
