### ISSUE TITLE
Signature verification with multiple certificates when validating SAML responses

### ISSUE THREAD

**Issue by nhosoya** [digidentity/libsaml#187]
I'm having a problem implementing SP with libsaml.

In libsaml, if the metadata contains multiple certificates and no KeyName is specified in the SAML response, `Saml::Util.verify_xml` will always verify the signature with the first certificate.
https://github.com/digidentity/libsaml/blob/8256fc64900c0ef73deff4ed9938d050e5aec5f4/lib/saml/complex_types/role_descriptor_type.rb#L30

This means that the signature verification will always fail if the second certificate is actually used.
In fact, even IdPs like Google and Azure AD do not specify the KeyName in the SAML response when there are multiple certificates. (KeyName does not even exist in metadata)
This causes the problem that there are times when the user cannot log in during certificate rotation.

How about changing the implementation (or providing it as an option) to try to verify signatures using all certificates included in the metadata?
This idea has been implemented in OSS such as ruby-saml and Keycloak.
https://github.com/onelogin/ruby-saml/blob/master/lib/onelogin/ruby-saml/response.rb#L884-L898
https://github.com/keycloak/keycloak/blob/8e6489459dac322bbc61b6a63b7cb2d5aa9870af/saml-core/src/main/java/org/keycloak/saml/processing/core/util/XMLSignatureUtil.java#L498-L513

---

I'd like to contribute with a PullRequest, but I'm not familiar with libsam's implementation so it's going to take some time.  I hope someone can help me.

~https://github.com/nhosoya/libsaml/commit/e3be603772419a873602578f6e325703551dafa9~ https://github.com/nhosoya/libsaml/commit/e4ac421100d4fe8c7c38b61cceb9d1712884a8ac
This change is sufficient to solve the problem I'm concerned about, but I still don't fully understand how this change will affect other features of libsaml.

**Comment by jdongelmans** [comment]
Hi @nhosoya,

Thank you for your time to write this issue. Indeed, we also have a similar project where key rotation without key names is happening so we have monkey patched our own apps SamlProvider to solve this. It basically looks the same as your proposed patch in https://github.com/nhosoya/libsaml/commit/e3be603772419a873602578f6e325703551dafa9

If you make a PR for this (preferably including specs) I'm happy to merge this in 🙂

**Comment by nhosoya** [comment]
Thanks for the valuable information. @jdongelmans 

There was a mistake in the commit in the description, so I fixed it.
