### ISSUE TITLE
Missing previously created issues

### ISSUE THREAD

**Issue by theghostwhoforks** [digidentity/libsaml#2]
Hello,

Something funny just happened. While I was trying to add a few more details to an earlier issue that I'd raised, all earlier issues went missing! [My previous issue](https://github.com/digidentity/libsaml/issues/65) now results in a 404.

I'm adding the details that I was attempting to add earlier here.
>
Thanks. I'll verify the behaviour of the DigestMethod and get back to you.
>
Regarding the rest, I'm adding a few more details that might be of help.
>
[When Saml::Util#decrypt_assertions is invoked] (https://github.com/digidentity/libsaml/blob/master/lib/saml/util.rb#L85) with the encrypted_assertion section of the XML listed above, it invokes [Xmlenc::EncryptedDocument#decrypt] (https://github.com/digidentity/xmlenc/blob/master/lib/xmlenc/encrypted_document.rb#L18). Inside this method, it loops over the 2 encrypted_keys and is able to successfully decrypt the encrypted data for the first encrypted key.
>
However, during the second iteration, [encrypted_data node](https://github.com/digidentity/xmlenc/blob/master/lib/xmlenc/encrypted_key.rb#L21) cannot be constructed as the [xpath used](https://github.com/digidentity/xmlenc/blob/master/lib/xmlenc/encrypted_key.rb#L50) cannot find the relevant EncryptedData node, which causes the issue reported.
>
Hope this helps.

Thanks! Please let me know if you need any additional details.

**Comment by JanDintel** [comment]
@theghostwhoforks Unfortunately the account got deleted, including all the issues. I've recreated your original issue in #1

**Comment by theghostwhoforks** [comment]
Ok. Thanks for adding the reference. I'll close this issue.
