### ISSUE TITLE
Possible bug - Should the x509 data in the KeyInfo remove new lines?

### ISSUE THREAD

**Issue by nddeluca** [digidentity/libsaml#53]
On https://github.com/digidentity/libsaml/blob/master/lib/saml/elements/key_info/x509_data.rb#L10, the certificate is base64 encoded and new lines are not removed.  However, in the readme, the example code and service provider metadata removes the new lines from the certificate.

I'm using your gem to auto-generate service provider metadata from stored options and it's not clear to me which is the correct approach.  Any guidance would be appreciated and thanks for the awesome gem !

**Comment by benoist** [comment]
Hi Nick,

Thank you for choosing our library.
Base64 adds newlines after encoding, but they are not used when decoding so either way is fine. I find it easier to have the new lines as you can see the closing tag as well when you read the XML file.

You can create a metadata action in your controller. The action could look something like this.
Note that the location and entity id are rails URL helper methods. You should replace them with your own ones.

```ruby
def metadata
  certificate_pem = File.read('file/to/certificate.pem')
  
  signing_key_descriptor    = Saml::Elements::KeyDescriptor.new(certificate: certificate_pem, use: 'signing')
  encryption_key_descriptor = Saml::Elements::KeyDescriptor.new(certificate: certificate_pem, use: 'encryption')

  assertion_consumer_service = Saml::Elements::SPSSODescriptor::AssertionConsumerService.new(
      binding:  Saml::ProtocolBinding::HTTP_ARTIFACT,
      index:    0,
      location: receive_artifact_sessions_url
  )

  sp_sso_descriptor = Saml::Elements::SPSSODescriptor.new(
      assertion_consumer_services: [assertion_consumer_service],
      key_descriptors:            [signing_key_descriptor, encryption_key_descriptor]
  )

  entity_descriptor                   = Saml::Elements::EntityDescriptor.new(entity_id: metadata_sessions_url)
  entity_descriptor.sp_sso_descriptor = sp_sso_descriptor

  render xml: entity_descriptor.to_xml
end
```

**Comment by nddeluca** [comment]
Thanks for the quick response!  That's good to know, I'll leave the new lines in then.  And awesome, a metadata action is what I'm working on right now so the example code really helps :+1:
