### ISSUE TITLE
How to populate DigestValue in the signed Info.

### ISSUE THREAD

**Issue by sahild** [digidentity/libsaml#79]
I am trying to add a siginature using `add_signature` present here:
https://github.com/digidentity/libsaml/blob/master/lib/saml/xml_helpers.rb#L5

but i am not sure where and how to calculate digest_value that is being passed to `SignedInfo` here:
https://github.com/digidentity/libsaml/blob/master/lib/saml/elements/signature.rb#L27

and hence DigestValue node in my final SAML node is always empty:
`<ds:DigestValue/>`

I am pretty sure i am doing something wrong but could not find anything in the code to figure this out.

Is it possible to add an example somewhere regarding this.

If you can let me know i can add a wiki page for the gem regarding this.

**Comment by benoist** [comment]
Hi,

Calling add_signature is not required if you use the util function for setting signature.
https://github.com/digidentity/libsaml/blob/master/lib/saml/util.rb#L45-L56

Using the util function for signing is also not required if you are using the correct binding objects to send the message:
https://github.com/digidentity/libsaml/tree/master/lib/saml/bindings
https://github.com/digidentity/libsaml/blob/master/lib/saml/bindings/http_post.rb#L10
https://github.com/digidentity/libsaml/blob/master/lib/saml/bindings/http_redirect.rb#L98
https://github.com/digidentity/libsaml/blob/master/lib/saml/bindings/http_artifact.rb#L37

Cheers,
Benoist

**Comment by sahild** [comment]
thanks @benoist . Thanks for pointing me in the right direction. and really appreciate writing this awesome gem, i just have 2 days experience in saml and i am happy to say that everything i learned about SAML is via the source code of your gem.
I will try out your approach and will let you know  and will also document it somewhere for other people too.
Thanks again!

**Comment by sahild** [comment]
Thank you @benoist . It worked out pretty great. i used this HTTP_POST bindings utility  as you suggested 
`Saml::Bindings::HTTPPost.create_form_attributes( saml_response_object)`
and got a digitally signed xml , base64 encoded and that i can easily add as a hidden param in my form POST.

**Comment by sahild** [comment]
Hi @benoist,
when i use this `Saml::Bindings::HTTPPost.create_form_attributes( saml_response_object)` it actually signs the saml response object.
But the Service provider is expecting a signed assertion instead.
i am able to sign the assertion also using this:
`signed_assertion_xml = Saml::Util.sign_xml( saml_assertion_object )` , but the problem is that it converts it into an xml and after that i am not able to use that assertion xml like this:
`Saml::Bindings::HTTPPost.create_form_attributes( Saml::Response.new(:assertion =>  signed_assertion_xml)` as it creates gibberish

Is it possible to sign the assertion and also be able to use it in HTTPPost binding.
Thanks in advance!
Regards
Sahil

**Comment by benoist** [comment]
Yes that's possible. After instantiating the Saml::Assertion you can simply call `add_signature`.
When you pass the Saml::Response with the assertion to the binding function, it will sign all elements that have a Signature element present. You don't have to do that yourself.

**Comment by sahild** [comment]
@benoist thank you! it worked out as you said. Just one last question( hopefully :) )
Is there anything i can change in this:
`Saml::Bindings::HTTPPost.create_form_attributes( Saml::Response.new(:assertion => saml_assertion_object.add_signature)`
So that it only signs the assertion but not the the Saml::Response object ( currently it is adding signature to both)

P.S: i promise i will add all this info on a wiki page :)

**Comment by benoist** [comment]
No worries :)

No that is not supported as it goes against the SAML security considerations. All outermost messages SHOULD be signed. So if you really want to do it without (and I'd strongly advice you not to do that), you'd have to copy the code from the binding and the sign function and omit the add_signature line. Something like this would work:

```ruby
def create_form_attributes(message, options = {})
  param = message.is_a?(Saml::ComplexTypes::StatusResponseType) ? "SAMLResponse" : "SAMLRequest"
  
  document = Xmldsig::SignedDocument.new(message.send("to_#{format}"))
  signed_message = document.sign do |data, signature_algorithm|
    message.provider.sign(signature_algorithm, data)
  end

  variables        = {}
  variables[param] = Saml::Encoding.encode_64(signed_message)
  variables["RelayState"] = options[:relay_state] if options[:relay_state]

  {
      location:  message.destination,
      variables: variables
  }
end
```

I must say again, this is really not save! No client should allow unsigned message.

Cheers
Benoist

**Comment by sahild** [comment]
@benoist thank you! it worked. It worked as you mentioned.
This is very useful information.
Forked the repo. I will submit a Pull Request shortly with this information shortly.
Thank you!
