### ISSUE TITLE
Ability To Specify A different Signature Algorithm.

### ISSUE THREAD

**Issue by sahild** [digidentity/libsaml#80]
Hi,
I was comparing the SAML generated and the sample SAML request i needed to create and noticed that signature algorithms are different.

`<ds:SignedInfo>
      <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
      <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
      <ds:Reference URI="#_7bf53f24a45449258e6a9dc9d575314e57ca9e15">
        <ds:Transforms>
          <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
          <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
            <ec:InclusiveNamespaces PrefixList="ds saml samlp xs"/>
          </ds:Transform>
        </ds:Transforms>
        <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
        <ds:DigestValue>N6RFW+/Y+PQXV6wks3oZqieraTJdxVr+9pQd8LIGwtQ=</ds:DigestValue>
      </ds:Reference>
    </ds:SignedInfo>`

`<ds:SignedInfo>
      <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
      <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
      <ds:Reference URI="#YdLC00_3TUAUV.gHa9jUb.4J5fP">
        <ds:Transforms>
          <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
          <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
        </ds:Transforms>
        <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
        <ds:DigestValue>/F6w5kUzhV6FINapRt/MkNr9Te8=</ds:DigestValue>
      </ds:Reference>
</ds:SignedInfo>`

this lead me to this line of code:
https://github.com/digidentity/libsaml/blob/master/lib/saml/elements/signature/signature_method.rb#L13

Is it possible to use a different signature algorithm like `http://www.w3.org/2000/09/xmldsig#rsa-sha1`

I am not even sure is at verification level it even matters, since it is mentioned in the Assertion which signature algorithm is used and the assertion should be verified against that only.

**Comment by benoist** [comment]
Yes thats definitely possible, however security considerations prescribe the use a minimum of SHA256 when used with the POST binding.
But you can always change the signature algorithm via the signature objects after calling add_signature.
The signing library will use the specified algorithm so all you have to do is set it by hand.

The reason this is kind of harder to do within the library is because its very insecure to do so. I would strongly advise you to stick to the standard and if someone is forcing you to use lesser security, I'd do everything to change their perspective. Using SHA1 and not signing outer messages leaves huge holes in the security of your application.

**Comment by sahild** [comment]
Thanks @benoist .
I have raised both these concerns with the SSO team of the concerned person, along with both these issues. They have agreed to make signing of outer messages compulsary but will only update the Algo in later releases.

And also as per your suggestion i was able to change the signature algo at the assertion level, but to change the algo of the outer message( at response level ) ( the one added here https://github.com/digidentity/libsaml/blob/master/lib/saml/util.rb#L46 )
i guess i need your previous solution of doing something like this:

`def create_form_attributes(message, options = {})
  param = message.is_a?(Saml::ComplexTypes::StatusResponseType) ? "SAMLResponse" : "SAMLRequest"
 message.add_signature
 message.add_signature
 message.signature.signed_info.signature_method.algorithm = 'http://www.w3.org/2000/09/xmldsig#rsa-sha1'
  document = Xmldsig::SignedDocument.new(message.send("to_#{format}"))
  signed_message = document.sign do |data, signature_algorithm|
    message.provider.sign(signature_algorithm, data)
  end

  variables        = {}
  variables[param] = Saml::Encoding.encode_64(signed_message)
  variables["RelayState"] = options[:relay_state] if options[:relay_state]

  {
      location:  message.destination,
      variables: variables
  }
end`

Please let me know if you have a better suggestion for this.
Regards
Sahil

**Comment by benoist** [comment]
That's how it should be done if you want to use sha1 for the outer message. Technically we could make some changes in the library to make this easier, however I won't add this because it's unsafe practice. Hope you understand :-). Glad to hear signing of outer messages is now mandatory.

**Comment by sahild** [comment]
Thanks @benoist. i understand , whats the use of digitally signing it if the algorithm to sign it is outdated and not secure!
Appreciate your feedback, will try my best to get it changed.
Regards
Sahil
