### ISSUE TITLE
RSA KeyValue tag in the KeyInfo.

### ISSUE THREAD

**Issue by sahild** [digidentity/libsaml#81]
Hi,

```
    <ds:KeyInfo>
      <ds:X509Data>
        <ds:X509Certificate>
          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        </ds:X509Certificate>
      </ds:X509Data>
      <ds:KeyValue>
        <ds:RSAKeyValue>
          <ds:Modulus>
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
          </ds:Modulus>
          <ds:Exponent>AQAB</ds:Exponent>
        </ds:RSAKeyValue>
      </ds:KeyValue>
    </ds:KeyInfo>
```

but my keyInfo tags looks something like this:

```
      <ds:KeyInfo>
        <ds:KeyName>8b020738a9974ddf495fdf275527ad0ecc437c02</ds:KeyName>
        <ds:X509Data>
          <ds:X509Certificate> Some text
</ds:X509Certificate>
        </ds:X509Data>
      </ds:KeyInfo>
```

I was going through the file here:
https://github.com/digidentity/libsaml/blob/master/lib/saml/elements/key_info.rb#L12-L14
And noticed KeyInfo do not have has_one :key_value .
I am not sure if this out of purpose? or this attribute is depreceted and no longer needed?
Any quick or non-quick solution to include this in the KeyInfo node.

Regards
Sahil

**Comment by sahild** [comment]
@benoist  sorry for bugging you with so many things in a single day :)

**Comment by benoist** [comment]
no problem, glad I can help :)

It's not required according to the Xmldsig specification. The information is already present in the X509Data. The Xmldsig specification has many ways to include key information. Using the certificate is again more secure as it's been verified by a trusted certificate authority (or at least it should be :)).
We've never had the requirement to include it as all signature verifiers we communicate with can already use X509Data or just use the keyname to search for key material in the metadata.
If you really need it (I'd try it without first), you can always create new signature elements and add them to the signature object. You can just model it according to the X509 data object. Perhaps a pull request? :)

**Comment by sahild** [comment]
thanks @benoist !
i will get back to you on both these things.
I am not in a position to test at the moment but i will confirm to you if it worked or not and even if it worked i will create a pull request for this thing.
Thanks for all your help!

**Comment by sahild** [comment]
@benoist just wanted to  confirm as you said it worked out without RSA KeyValue tag and apparently this tag was not needed at all. Just keeping it open so that i remember i have to submit a pull request here.
Regards
Sahil
